version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      # trigger the integration tests here
      - echo 'Running integration tests'
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - . ./assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - python -m unittest discover tests/integration

